### ISSUE TITLE
I encountered this error can you help me out ?

### ISSUE THREAD

**Issue by emortoo** [nicknochnack/ReactChatBot#1]
[nodemon] restarting due to changes...
[nodemon] starting `node server server.js`
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module './routes/api/watson'
Require stack:
- /Users/emo/Desktop/chatbot /server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/emo/Desktop/chatbot /server.js:10:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/emo/Desktop/chatbot /server.js' ]
}

**Comment by nicknochnack** [comment]
Hey sure! Did you have the watson.js file inside the routes/api folder?

**Comment by emortoo** [comment]
Yes I did but it was still giving an error but I downloaded you files on GitHub and replaced it. I'm pass that stage now but when I run it in the postman 
"There was an error processing your request.” This error shows up and I’m stuck. 

Thank you for getting back to me on this issue I have so many questions to ask and learn in Watson Assistant from an expert like you. If you have the time let me know so we do zoom meeting. 

Regards 

Emmanuel

**Comment by emortoo** [comment]
Not Found: Resource not found
    at RequestWrapper.formatError (/Users/emo/Downloads/ReactChatBot-master/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:216:21)
    at /Users/emo/Downloads/ReactChatBot-master/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:204:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusText: 'Not Found',
  status: 404,
  code: 404,
  body: '{"error":"Resource not found","code":404}',
  headers: {
    'content-type': 'application/json; charset=utf-8',
    'content-length': '41',
    'access-control-allow-origin': '*',
    'access-control-allow-methods': 'GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS',
    'access-control-allow-headers': 'Content-Type, Content-Length, Authorization, X-Watson-Authorization-Token, X-WDC-PL-OPT-OUT, X-Watson-UserInfo, X-Watson-Learning-Opt-Out, X-Watson-Metadata',
    'access-control-max-age': '3600',
    'content-security-policy': "default-src 'none'",
    'x-dns-prefetch-control': 'off',
    'x-frame-options': 'SAMEORIGIN',
    'strict-transport-security': 'max-age=31536000; includeSubDomains;',
    'x-download-options': 'noopen',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '1; mode=block',
    'x-response-time': '0.795ms',
    'x-global-transaction-id': 'ecc84e2e0771c62fdc7d2a55b01e51df',
    'x-dp-watson-tran-id': 'ecc84e2e0771c62fdc7d2a55b01e51df',
    'x-edgeconnect-midmile-rtt': '113',
    'x-edgeconnect-origin-mex-latency': '341',
    date: 'Fri, 19 Jun 2020 14:28:46 GMT',
    connection: 'close'
  }
}

**Comment by arpitdalal** [comment]
@emortoo you need to have node.js installed in your machine and if you do just run `npm i` into the root folder and the client folder and also don't forget to put your IBM Watson Assistant API key credentials into the .env file and everything will work just fine.

**Comment by nicknochnack** [comment]
Thanks @arpitdalalm, also @emortoo can you cd into ./client and run `npm i` from there as well to install the client dependencies.
