### ISSUE TITLE
Getting HTTP 431 error while getting session and posting messages

### ISSUE THREAD

**Issue by arpitdalal** [nicknochnack/ReactChatBot#3]
error: `Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR`
Back-end runs perfectly via postman but when opening the app in the browser, the axiox request to `/api/watson/session` and `/api/watson/message` gives me this^ error in the browser console.
I tried adding localhost:5000 in front of the axios requests but didn't help, can you please tell me how can I solve this error?

**Comment by nicknochnack** [comment]
@arpitdalalm can you clear the session key from local storage and test again. I noticed this bug was happening intermittently when developing, working on a fix to handle the session tokens at the moment.

**Comment by arpitdalal** [comment]
@nicknochnack it is fixed on my machine, I had a bug in my code that I was using https://localhost:5000 instead of http://localhost:5000 and I had to use CORS npm package in my backend to not have cross-origin errors. That fixed it for me.
